var map_config = {
	'default':{
		'bordercolor':'#9CA8B6', //inter-state borders
		'lakescolor':'#66CCFF', //lakes color
		'shadowcolor':'#000000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'namescolor':'#666666', //color of the abbreviations 
		'namesShadowColor':'#666666', //tooltip shadow color
		'msg_title':'DEFAULT TITLE',//default title text
		'msg_data': 'Default Data',//default content text
	},
	'map_1':{
		'namesId':'AL',//name's ID (Don't change it)
		'name': 'ALABAMA',  //state name
		'data':'Data of Alabama',//data appears in the text box when a user clicks this state
		'upcolor':'#EBECED', //state's color when page loads
		'overcolor':'#99CC00', //state's color when mouse hover
		'downcolor':'#993366',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'namesId':'AK',
		'name': 'ALASKA',
		'data':'Data of Alaska',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'ARIZONA',		
		'data':'Data of Arizona',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'ARKANSAS',
		'data':'Data of Arkansas',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'CALIFORNIA',
		'data':'Data of California',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'COLORADO',
		'data':'Data of Colorado',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'CONNECTICUT',
		'data':'Data of Connecticut',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'DELAWARE',
		'data':'Data of Delaware',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'FLORIDA',
		'data':'Data of Florida',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'GEORGIA',
		'data':'Data of Georgia',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'HAWAII',
		'data':'Data of Hawaii',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'IDAHO',
		'data':'Data of Idaho',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'ILLINOIS',
		'data':'Data of Illinois',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'INDIANA',
		'data':'Data of Indiana',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'IOWA',
		'data':'Data of Iowa',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'KANSAS',
		'data':'Data of Kansas',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'KENTUCKY',
		'data':'Data of Kentucky',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'LOUISIANA',
		'data':'Data of Louisiana',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'MAINE',
		'data':'Data of Maine',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'MARYLAND',
		'data':'Data of Maryland',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'MASSACHUSETTS',
		'data':'Data of Massachusetts',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'MICHIGAN',
		'data':'Data of Michigan',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'MINNESOTA',
		'data':'Data of Minnesota',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'MISSISSIPPI',
		'data':'Data of Mississippi',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'MISSOURI',
		'data':'Data of Missouri',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'MONTANA',
		'data':'Data of Montana',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'NEBRASKA',
		'data':'Data of Nebraska',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'NEVADA',
		'data':'Data of Nevada',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'NEW HAMPSHIRE',
		'data':'Data of New Hampshire',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'NEW JERSEY',
		'data':'Data of New Jersey',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'NEW MEXICO',
		'data':'Data of New Mexico',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'NEW YORK',
		'data':'Data of New York',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'NORTH CAROLINA',
		'data':'Data of North Carolina',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'NORTH DAKOTA',
		'data':'Data of North Dakota',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'OHIO',
		'data':'Data of Ohio',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'OKLAHOMA',
		'data':'Data of Oklahoma',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'OREGON',
		'data':'Data of Oregon',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'PENNSYLVANIA',
		'data':'Data of Pennsylvania',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'RHODE ISLAND',
		'data':'Data of Rhode Island',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'SOUTH CAROLINA',
		'data':'Data of South Carolina',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'SOUTH DAKOTA',
		'data':'Data of South Dakota',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'TENNESSEE',
		'data':'Data of Tennessee',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'TEXAS',
		'data':'Data of Texas',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'UTAH',
		'data':'Data of Utah',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'VERMONT',
		'data':'Data of Vermont',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'VIRGINIA',
		'data':'Data of Virginia',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'WASHINGTON',
		'data':'Data of Washington',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'WEST VIRGINIA',
		'data':'Data of West Virginia',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'WISCONSIN',
		'data':'Data of Wisconsin',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'WYOMING',
		'data':'Data of Wyoming',
		'upcolor':'#EBECED',
		'overcolor':'#99CC00',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_51':{
		'namesId':'DC',
		'name': 'WASHINGTON DC',
		'data':'Data of Washington DC',
		'upcolor':'#FF6600',
		'overcolor':'#0000FF',
		'downcolor':'#993366',
		'enable':true,
	},
}
